version: '2'
volumes:
  gitlab-app-data:
    driver: ${volumedriver}
  gitlab-log-data:
    driver: ${volumedriver}
  gitlab-conf-files:
    driver: ${volumedriver}

services:
  lb:
    image: rancher/lb-service-haproxy:v0.9.6
    expose:
    - 80:80/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin,agent
      io.rancher.container.agent_service.drain_provider: 'true'
      io.rancher.container.create_agent: 'true'
      https: 'true'
  gitlab-server:
    ports:
      - ${ssh_port}:22/tcp
    labels:
      io.rancher.container.hostname_override: container_name
    image: gitlab/gitlab-ce:11.9.6-ce.0
    volumes:
      - gitlab-app-data:/var/opt/gitlab
      - gitlab-log-data:/var/log/gitlab
      - gitlab-conf-files:/etc/gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |-
        external_url 'https://gitlab.${gitlab_domain}'
        gitlab_rails['gitlab_ssh_host'] = 'gitlab.${gitlab_domain}'
        gitlab_rails['gitlab_email_enabled'] = true
        gitlab_rails['gitlab_email_from'] = '${gitlab_email_from}'
        gitlab_rails['gitlab_email_display_name'] = '${gitlab_email_display_name}'
        gitlab_rails['gitlab_email_reply_to'] = '${gitlab_email_reply_to}''
        gitlab_rails['gravatar_plain_url'] = 'https://secure.gravatar.com/avatar/%{hash}?s=%{size}&d=identicon'
        gitlab_rails['gravatar_ssl_url'] = 'https://secure.gravatar.com/avatar/%{hash}?s=%{size}&d=identicon'
        gitlab_rails['gitlab_shell_ssh_port'] = '${ssh_port}'
        gitlab_rails['smtp_enable'] = '${smtp_enable}'
        gitlab_rails['smtp_address'] = '${smtp_address}'
        gitlab_rails['smtp_port'] = '${smtp_port}'
        gitlab_rails['smtp_domain'] = '${smtp_domain}'
        gitlab_rails['smtp_user_name'] = '${smtp_user_name}'
        gitlab_rails['smtp_password'] = '${smtp_password}'
        gitlab_rails['smtp_authentication'] = '${smtp_authentication}'
        gitlab_rails['smtp_enable_starttls_auto'] = '${smtp_enable_starttls_auto}'
        gitlab_rails['smtp_tls'] = '${smtp_tls}'
        gitlab_rails['smtp_openssl_veryfy_mode'] = '${smtp_openssl_veryfy_mode}'
        gitlab_rails['manage_backup_path'] = true
        gitlab_rails['backup_path'] = '/var/opt/gitlab/backups'
        gitlab_rails['backup_archive_permissions'] = 0644
        gitlab_rails['backup_pg_schema'] = 'public'
        gitlab_rails['backup_keep_time'] = 604800
        registry_external_url 'https://registry.${gitlab_domain}'
        gitlab_rails['registry_enabled'] = true
        gitlab_rails['registry_host'] = 'registry.${gitlab_domain}'
        gitlab_rails['registry_api_url'] = 'http://localhost:5000'
        registry['enable'] = true
        registry['token_realm'] = 'https://gitlab.${gitlab_domain}'
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
        nginx['proxy_set_headers'] = {
         'Host' => '$$http_host_with_default',
         'X-Real-IP' => '$$remote_addr',
         'X-Forwarded-For' => '$$proxy_add_x_forwarded_for',
         'X-Forwarded-Proto' => 'https',
         'X-Forwarded-Ssl' => 'on',
         'Upgrade' => '$$http_upgrade',
         'Connection' => '$$connection_upgrade'
        }
        registry_nginx['enable'] = true
        registry_nginx['listen_port'] = 80
        registry_nginx['listen_https'] = false
        registry_nginx['proxy_set_headers'] = {
         'Host' => '$$http_host',
         'X-Real-IP' => '$$remote_addr',
         'X-Forwarded-For' => '$$proxy_add_x_forwarded_for',
         'X-Forwarded-Proto' => 'https',
         'X-Forwarded-Ssl' => 'on'
        }
        registry_nginx['custom_gitlab_server_config'] = 'proxy_cache_convert_head off;'